Postman config change Eth1/1 to Eth1/4 (NX-API)
When trying to add a description to Eth1/1 in NX-OS sandbox, it fails because the default setup sets Eth1/1 in a port channel:

```
ERROR: : port already in a port-channel, no config allowed
```

So let's configure Eth1/4 instead, and everything works fine.